### ISSUE TITLE
Commands as reward are still executed on LP

### ISSUE THREAD

**Issue by goldenlib** [UltraCosmetics/UltraCosmetics#317]
### Check if the issue is fixed in dev builds

- [X] I have confirmed that the issue is present on the latest dev build

### What steps will reproduce the issue?

1. you have to use LP and set a command has reward. In the command section, put a permission and a context. (for exemple: i putted the permission to fly only in the lobby)
2. When you open the treasure chest, the plugin don't reconice the "cancel-if-permission" because of the context given previously

EX:
```
      flymode:
        Name: <bold><blue>Fly in the lobby
        Material: ELYTRA
        Enabled: true
        Chance: 2
        Message:
          enabled: true
        Cancel-If-Permission: essentials.fly
        Commands:
        - lp user %name% permission set essentials.fly true world=Spawn
 ```

### What was supposed to happen?

Because the player has the permission already, they should not be able to obtain it again.

### What happened instead?

The plugin seems to not reconize the permission because of the context and gtry to give the permission again. In the console we can see LP saying the player already has the permission set.

### What version of UltraCosmetics are you using? Do not say 'latest'.

UltraCosmetics-3.7-DEV-b2

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

paper-1.21-109

### What plugins do you have installed?

LuckyPerm
Essentials
